package iozhik.vk

final case class Application(id: Int,
                             title: String,
                             icon278: String,
                             icon139: String,
                             icon150: String,
                             icon75: String,
                             banner560: String,
                             banner1120: String,
                             `type`: String,
                             section: String,
                             authorUrl: String,
                             authorId: Int,
                             authorGroup: Int,
                             membersCount: Int,
                             publishedDate: Int,
                             catalogPosition: Int,
                             international: Boolean,
                             leaderboardType: Integer,
                             genreId: Int,
                             genre: String,
                             platformId: String,
                             isInCatalog: Boolean,
                             friends: Vector[Int],
                             installed: Boolean,
                             isHtml5App: Option[Boolean] = Option.empty,
                             screenOrientation: Int,
                             mobileControlsType: Integer,
                             mobileViewSupportType: Option[Boolean] = Option.empty,
                             description: Option[String] = Option.empty,
                             screenName: Option[String] = Option.empty,
                             icon16: Option[String] = Option.empty,
                             screenshots: Vector[Photo],
                             pushEnabled: Boolean)
